on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: mvn clean package -DskipTests

      - name: Prepare Assets
        run: |
          mkdir jafax
          mkdir jafax/results
          cp README.md jafax/README.md
          cp target/jafax.jar jafax/jafax.jar
          cp bin/jafax.sh jafax/jafax.sh
          cp bin/jafax.bat jafax/jafax.bat
          cp instrument.yml jafax/instrument.yml
          chmod +x jafax/jafax.sh

      - name: Create Archive
        run: zip -r jafax.zip jafax

      - name: Extract Semver
        id: semver_parser
        run: |
          semver=${TAG#"refs/tags/v"}
          semver=${semver%"-voyager"}

          echo ::set-output name=semver::$semver
        env:
          TAG: ${{ github.ref }}

      - name: Prepare Release Notes
        run: touch ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: JaFaX ${{ steps.semver_parser.outputs.semver }}
          body_path: ${{ github.workspace }}/releaseNotes/v${{ steps.semver_parser.outputs.semver }}.md
          body: ""
          prerelease: false
          draft: false
          fail_on_unmatched_files: true
          files: jafax.zip

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dxworks'

      - name: Prepare Node App
        run: |
          npm install
          npm run build

      - name: Setup Version
        run: json -I -f package.json -e "this.version='$VERSION'"
        env:
          VERSION: ${{ steps.semver_parser.outputs.semver }}

      - name: Publish NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

